version: '3.8'
services:
  cvtserver:
    image: kelvinmaxwell/cvtserver-springboot-images:latest
    ports:
      - "9099:9099"
    networks:
      - my_network
  cvtgateway:
    image: kelvinmaxwell/gateway-springboot-images:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3306/forge
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Karimax@2023
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://cvtserver:9099/eureka
    networks:
      - my_network
  cvtmain:
    image: kelvinmaxwell/cvtmain-springboot-images:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3306/forge
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Karimax@2023
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://cvtserver:9099/eureka
    networks:
      - my_network

  towingambulanceservice:
    image: kelvinmaxwell/towingambulance-springboot-images:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3306/forge
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Karimax@2023
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://cvtserver:9099/eureka
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
