logging:
  level:
    cvt:
      karimax:
        cvtgateway: ERROR
    org:
      hibernate: ERROR
    root: ERROR

server:
  port: 8080


spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      retry:
        enabled: true
      cache:
        ttl: 2s
    gateway:
      httpclient:
        pool:
          max-connections: 8000
          max-idle-time: 60s  # Helps keep unused connections active
          max-life-time: 160s  # Prevents too many stale connections
          acquire-timeout: 10000  # Ensures connections are available quickly
        connect-timeout: 5000     # 5 seconds for new connections
        response-timeout: 60000   # 30 seconds for full response
      routes:
        - id: cvt-main
          uri: lb://cvt-main
          predicates:
            - Path=/api/v1/auth/**,/api/v1/employees/**,/api/v1/garages/**,/api/v1/jobcards/**,/api/v1/mechtypes/**,/api/v1/mpesa/**,/api/v1/inspection/**,/api/v1/products/**,/api/v1/quotations/**,/api/v1/services/**,/api/v1/users/**,/api/v1/vehicles/**
        - id: towing-ambulance-service
          uri: lb://towing-ambulance-service
          predicates:
            - Path=/api/v1/towingambulance/**,/api/v1/services_at/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
                methods: GET
                backoff:
                  firstBackoff: 2000
                  maxBackoff: 15000
                  factor: 2




    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://cvtserver:9099/eureka
  instance:
    prefer-ip-address: true